// Mock team service
import type { Team, TeamMember } from "./types"
import { supabase } from "./supabase"
import { authService } from "./auth-service"

// Mock team data
const MOCK_TEAM: Team = {
  id: "team-1",
  name: "Acme Development",
  inviteCode: "TEAM-123-ABC",
  createdAt: new Date().toISOString(),
  ownerId: "user-1",
}

// Mock team members
const MOCK_TEAM_MEMBERS: TeamMember[] = [
  {
    id: "user-1",
    name: "John Doe",
    email: "john@example.com",
    role: "Owner",
    joinedAt: new Date().toISOString(),
  },
  {
    id: "user-2",
    name: "Jane Smith",
    email: "jane@example.com",
    role: "Admin",
    joinedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "user-3",
    name: "Bob Johnson",
    email: "bob@example.com",
    role: "Member",
    joinedAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "user-4",
    name: "Alice Williams",
    email: "alice@example.com",
    role: "Member",
    joinedAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

// Mock storage keys
const TEAM_STORAGE_KEY = "pulsecheck_team"

export const teamService = {
  // Create a new team
  async createTeam(name: string): Promise<Team> {
    const currentUser = await authService.getCurrentUser()
    if (!currentUser) throw new Error("User not authenticated")

    // Insert new team
    const { data: teamData, error: teamError } = await supabase
      .from("teams")
      .insert({
        name,
        invite_code: null, // Will be generated by database trigger
        owner_id: currentUser.id,
      })
      .select()
      .single()

    if (teamError) throw teamError

    // Add the current user as team owner
    const { error: memberError } = await supabase.from("team_members").insert({
      team_id: teamData.id,
      user_id: currentUser.id,
      role: "Owner",
    })

    if (memberError) throw memberError

    return {
      id: teamData.id,
      name: teamData.name,
      inviteCode: teamData.invite_code,
      createdAt: teamData.created_at,
      ownerId: teamData.owner_id,
    }
  },

  // Join an existing team
  async joinTeam(inviteCode: string): Promise<Team> {
    const currentUser = await authService.getCurrentUser()
    if (!currentUser) throw new Error("User not authenticated")

    // Find team by invite code
    const { data: teamData, error: teamError } = await supabase
      .from("teams")
      .select()
      .eq("invite_code", inviteCode)
      .single()

    if (teamError) throw new Error("Invalid invite code")

    // Check if user is already a member
    const { data: existingMember } = await supabase
      .from("team_members")
      .select()
      .eq("team_id", teamData.id)
      .eq("user_id", currentUser.id)
      .maybeSingle()

    if (existingMember) {
      // User is already a member, just return the team
    } else {
      // Add user as team member
      const { error: memberError } = await supabase.from("team_members").insert({
        team_id: teamData.id,
        user_id: currentUser.id,
        role: "Member",
      })

      if (memberError) throw memberError
    }

    return {
      id: teamData.id,
      name: teamData.name,
      inviteCode: teamData.invite_code,
      createdAt: teamData.created_at,
      ownerId: teamData.owner_id,
    }
  },

  // Get the current user's teams
  async getUserTeams(): Promise<Team[]> {
    const currentUser = await authService.getCurrentUser()
    if (!currentUser) throw new Error("User not authenticated")

    // Get all teams the user is a member of
    const { data: teamMembers, error: memberError } = await supabase
      .from("team_members")
      .select("team_id")
      .eq("user_id", currentUser.id)

    if (memberError) throw memberError
    if (!teamMembers.length) return []

    // Get team details
    const teamIds = teamMembers.map((member) => member.team_id)
    const { data: teamsData, error: teamsError } = await supabase
      .from("teams")
      .select()
      .in("id", teamIds)

    if (teamsError) throw teamsError

    return teamsData.map((team) => ({
      id: team.id,
      name: team.name,
      inviteCode: team.invite_code,
      createdAt: team.created_at,
      ownerId: team.owner_id,
    }))
  },

  // Get the current team
  async getCurrentTeam(): Promise<Team> {
    const teams = await this.getUserTeams()
    if (!teams.length) {
      // If no teams found, create a default team
      return this.createTeam("My Team")
    }
    return teams[0] // Return the first team for now
  },

  // Get team members
  async getTeamMembers(teamId: string): Promise<TeamMember[]> {
    // Get all members of the team with join to users
    const { data, error } = await supabase
      .from("team_members")
      .select(`
        id,
        role,
        joined_at,
        user_id,
        users:user_id (
          name,
          email,
          avatar_url
        )
      `)
      .eq("team_id", teamId)

    if (error) throw error

    return data.map((item) => ({
      id: item.user_id,
      name: item.users.name,
      email: item.users.email,
      role: item.role as "Owner" | "Admin" | "Member",
      avatarUrl: item.users.avatar_url,
      joinedAt: item.joined_at,
    }))
  },

  // Invite a new member
  async inviteMember(teamId: string, email: string): Promise<void> {
    // In a production app, you would send an email with invite link
    // For this MVP, we'll just log the invite code
    
    // Get the team invite code
    const { data: teamData, error: teamError } = await supabase
      .from("teams")
      .select("invite_code")
      .eq("id", teamId)
      .single()

    if (teamError) throw teamError
    
    console.log(`Invitation link for ${email}: ${window.location.origin}/join?code=${teamData.invite_code}`)
  },

  // Remove a team member
  async removeMember(teamId: string, memberId: string): Promise<void> {
    const { error } = await supabase
      .from("team_members")
      .delete()
      .eq("team_id", teamId)
      .eq("user_id", memberId)

    if (error) throw error
  },

  // Update team settings
  async updateTeam(teamId: string, data: Partial<{ name: string }>): Promise<Team> {
    const { data: teamData, error } = await supabase
      .from("teams")
      .update(data)
      .eq("id", teamId)
      .select()
      .single()

    if (error) throw error

    return {
      id: teamData.id,
      name: teamData.name,
      inviteCode: teamData.invite_code,
      createdAt: teamData.created_at,
      ownerId: teamData.owner_id,
    }
  },
}
